name: long_life_burning
description: Application community for workout.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 0.5.3+1
  background_fetch: ^0.2.0
  intl: ^0.15.8
  date_utils: ^0.1.0+2
  simple_gesture_detector: ^0.1.3
  #page_transition: ^1.1.0
  #flutter_local_notifications: ^0.7.1+1
  #percent_indicator: ^2.1.1
  #font_awesome_flutter: ^8.4.0

  # Authentication
  #firebase_auth: ^0.11.1+6
  #google_sign_in: ^4.0.2
  #flutter_facebook_login: ^2.0.1
  #flutter_auth_buttons: ^0.5.0

  # Database
  #sqflite: ^1.1.0
  #firebase_storage: ^3.0.1
  #firebase_database: ^3.0.2
  #cloud_firestore: ^0.12.3

  # Map
  #location: ^2.3.5
  #geolocator: ^5.0.0
  #google_maps_flutter: ^0.5.16

  # Pedometer
  #pedometer: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/burn.png
    - assets/icons/distance.png
    - assets/icons/runner.png
    - assets/images/weather-bk.png
    - assets/images/weather-bk_enlarged.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/sarabun/Sarabun-Light.ttf
        - asset: assets/fonts/sarabun/Sarabun-ExtraLight.ttf
        - asset: assets/fonts/sarabun/Sarabun-Medium.ttf
        - asset: assets/fonts/sarabun/Sarabun-Thin.ttf
          style: normal # italic or normal

    - family: Sarabun-Italic
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/sarabun/Sarabun-Italic.ttf
        - asset: assets/fonts/sarabun/Sarabun-LightItalic.ttf
        - asset: assets/fonts/sarabun/Sarabun-ExtraLightItalic.ttf
        - asset: assets/fonts/sarabun/Sarabun-MediumItalic.ttf
        - asset: assets/fonts/sarabun/Sarabun-ThinItalic.ttf
          style: italic # italic or normal

    - family: Sarabun-Bold
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
        - asset: assets/fonts/sarabun/Sarabun-SemiBold.ttf
        - asset: assets/fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 700 # between 100 and 900

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700 # between 100 and 900
