name: long_life_burning
description: Application community for workout. Supported both Android and iOS. Bachelor's Degree Project (Thesis).

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0
author: Sukawit Charoendet <sukawit.ch@hotmail.com>
homepage: https://github.com/skwcrd/long-life-burning

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # Stage management
  get: ^4.1.4

  # Firebase
  firebase_analytics: ^8.1.0
  firebase_crashlytics: ^2.0.4
  cloud_firestore: ^2.2.0

  # Authentication
  crypto: ^3.0.1
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0

  # Notify
  # badges: ^2.0.1
  # flutter_app_badger: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0

  # Database
  # sqflite: ^2.0.0+3
  get_storage: ^2.0.2
  # shared_preferences: ^2.0.5

  # Map
  # location: ^4.1.1
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.6
  # googleapis: ^3.0.0
  # google_maps_webservice: ^0.0.19

  # Health
  health: ^3.0.6
  pedometer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  integration_test:
    sdk: flutter

  # built_value: ^8.0.6
  # build_runner: ^2.0.4
  # built_collection: ^5.0.0

  # json_annotation: ^4.0.1
  # json_serializable: ^4.1.3

  test:
  drive:
  mockito:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/