name: long_life_burning
description: Application community for workout.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_platform_widgets: ^0.10.0
  shared_preferences: 0.5.3+1
  background_fetch: ^0.2.0
  #page_transition: ^1.1.0
  #flutter_local_notifications: ^0.7.1+1

  # Authentication
  #firebase_auth: ^0.11.1+6
  #google_sign_in: ^4.0.2
  #flutter_facebook_login: ^2.0.1
  #flutter_auth_buttons: ^0.5.0

  # Database
  #sqflite: ^1.1.0
  #firebase_storage: ^3.0.1
  #firebase_database: ^3.0.2
  #cloud_firestore: ^0.12.3

  # Map
  #location: ^2.3.5
  #geolocator: ^5.0.0
  #google_maps_flutter: ^0.5.16

  # Pedometer
  #pedometer: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
  #  - assets/
    - locale/i18n_en.json
    - locale/i18n_th.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
        - asset: assets/fonts/sarabun/Sarabun-Italic.ttf
        - asset: assets/fonts/sarabun/Sarabun-BoldItalic.ttf
          style: normal # italic or normal

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700 # between 100 and 900
