name: long_life_burning
description: Application community for workout.
publish_to: 'none'
version: 1.0.0
author: Sukawit Charoendet <sukawit.ch@hotmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/