name: long_life_burning
description: Application community for workout.
version: 1.0.0+1
author: Long Life Burning <long.life.burning.1@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.15.8
  cached_network_image: ^1.1.1
  #uuid: ^2.0.2
  background_fetch: ^0.2.0
  #connectivity: ^0.4.4
  #scoped_model: ^1.0.1
  #url_launcher: ^5.1.2
  #permission_handler: ^3.2.2
  #provider: ^3.1.0
  path_provider: ^1.3.0
  #flutter_redux: ^0.5.3
  #page_transition: ^1.1.4
  #percent_indicator: ^2.1.1+1
  #font_awesome_flutter: ^8.5.0

  #Firebase
  firebase_auth: ^0.14.0+5
  #cloud_firestore: ^0.12.9+4
  #firebase_storage: ^3.0.6
  #firebase_messaging: ^5.1.5
  #firebase_database: ^3.0.7
  #cloud_functions: ^0.4.1+1
  #firebase_core: ^0.4.0+9
  #firebase_analytics: ^5.0.2

  # Notify
  flutter_local_notifications: ^0.8.2+1
  #badges: ^1.1.0

  # Share
  #share: ^0.6.2+1
  #esys_flutter_share: ^1.0.2

  # Authentication
  #google_sign_in: ^4.0.7
  #flutter_facebook_login: ^2.0.1

  # Database
  sqflite: ^1.1.6+4
  #shared_preferences: ^0.5.3+4

  # Map
  flutter_map: ^0.7.2
  latlong: ^0.6.1
  #location: ^2.3.5
  #google_maps_flutter: ^0.5.21
  #geolocator: ^5.1.3

  # Pedometer
  fit_kit: ^0.0.5
  #pedometer: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  
  test: any
  #gherkin: ^1.0.4
  #flutter_gherkin: ^1.0.5
  #mockito: ^4.1.0
  #ozzie: ^2.2.3
  #pedantic: ">=1.5.0 <=1.8.0"

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # style italic or normal
    # weight between 100 and 900
    - family: CupertinoIcons
      fonts:
        - asset: assets/fonts/CupertinoIcons.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/raleway/Raleway-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/raleway/Raleway-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/raleway/Raleway-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/raleway/Raleway-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/roboto/Roboto-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic
