name: long_life_burning
description: Application community for workout.
version: 1.0.0+1
author: Long Life Burning <long.life.burning.1@gmail.com>
homepage: https://github.com/skwcrd/long-life-burning

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.15.8
  cached_network_image: ^1.1.0
  shared_preferences: ^0.5.3+4
  background_fetch: ^0.2.0
  #page_transition: ^1.1.0
  #flutter_local_notifications: ^0.7.1+1
  #percent_indicator: ^2.1.1
  #font_awesome_flutter: ^8.4.0

  # Authentication
  #firebase_auth: ^0.11.1+6
  #google_sign_in: ^4.0.2
  #flutter_facebook_login: ^2.0.1
  #flutter_auth_buttons: ^0.5.0

  # Database
  #sqflite: ^1.1.0
  #firebase_storage: ^3.0.1
  #firebase_database: ^3.0.2
  #cloud_firestore: ^0.12.3

  # Map
  flutter_map: ^0.5.0
  latlong: ^0.6.1
  #location: ^2.3.5
  #geolocator: ^5.0.0
  #google_maps_flutter: ^0.5.16

  # Pedometer
  #pedometer: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    # style italic or normal
    # weight between 100 and 900
    - family: CupertinoIcons
      fonts:
        - asset: assets/fonts/CupertinoIcons.ttf

    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/sarabun/Sarabun-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/sarabun/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800
